### ISSUE TITLE
Players not teleporting to island

### ISSUE THREAD

**Issue by Vxrtebs** [BG-Software-LLC/SuperiorSkyblock2#1392]
### Minecraft's Version

1.17.1 purpur

### Plugin's Version

SuperiorSkyblock2-2022.8.1-b839

### Describe the bug

when player type /is go is says on the chat that he have been teleported to his island, but he is getting teleported in the spawn, or sometimes they are getting teleported to the island but they cant break anything or open chests

### To Reproduce

idk it start to happen when like 50+ islands are created

### Additional Information

being teleported on spawn: https://cdn.discordapp.com/attachments/1021835071696666715/1025682011572162660/video_20221001_101149.mp4

not able to break or open anything: https://cdn.discordapp.com/attachments/1026214453538193458/1026217179202461736/2022-10-02_14-39-41_-_blur.mp4

**Comment by OmerBenGera** [comment]
Update to latest dev build, check if it fixes the issue.

**Comment by Vxrtebs** [comment]
wont this remove other players islands?

**Comment by Vxrtebs** [comment]
@OmerBenGera

**Comment by OmerBenGera** [comment]
> wont this remove other players islands?

No, why would it?
Take a backup if you are afraid

**Comment by Vxrtebs** [comment]
> No, why would it? Take a backup if you are afraid

i installed the version 848 on my server and the bug still occurs

**Comment by Vxrtebs** [comment]
@OmerBenGera

**Comment by Vxrtebs** [comment]
> Check out for errors, let me know if you find any. Btw, there's no need to mention me.

theres no errors in the logs

**Comment by OmerBenGera** [comment]
> > Check out for errors, let me know if you find any. Btw, there's no need to mention me.
> 
> theres no errors in the logs

Mind sending me your logs file, I'd like to take a look at it myself as well.

**Comment by WarnDa** [comment]
On latest dev build, when you restart, users aren't member anymore of their island, and it creates a new island when they do /is

**Comment by OmerBenGera** [comment]
> On latest dev build, each restart, users aren't member anymore of their island, and it creates a new island when they do /is
> 
> and islands aren't save in database : [SuperiorSkyblock2] Starting to load islands... [SuperiorSkyblock2] Finished loading 0 islands (Took 5ms)

Are there any islands in the database..?

**Comment by WarnDa** [comment]
> > On latest dev build, each restart, users aren't member anymore of their island, and it creates a new island when they do /is
> > and islands aren't save in database : [SuperiorSkyblock2] Starting to load islands... [SuperiorSkyblock2] Finished loading 0 islands (Took 5ms)
> 
> Are there any islands in the database..?
![image](https://user-images.githubusercontent.com/31826333/193647214-e5e3e1c7-dd80-4796-9b50-a083fd5c83b6.png)
nop (this is after a restart, and before the restart I created an island)

**Comment by OmerBenGera** [comment]
> > > On latest dev build, each restart, users aren't member anymore of their island, and it creates a new island when they do /is
> > > and islands aren't save in database : [SuperiorSkyblock2] Starting to load islands... [SuperiorSkyblock2] Finished loading 0 islands (Took 5ms)
> > 
> > 
> > Are there any islands in the database..?
> > ![image](https://user-images.githubusercontent.com/31826333/193647214-e5e3e1c7-dd80-4796-9b50-a083fd5c83b6.png)
> > nop (this is after a restart, and before the restart I created an island)

Weird, looks like your database got wiped?
Are you able to restore a backup (The plugin automatically makes backups)

**Comment by WarnDa** [comment]
> > > > On latest dev build, each restart, users aren't member anymore of their island, and it creates a new island when they do /is
> > > > and islands aren't save in database : [SuperiorSkyblock2] Starting to load islands... [SuperiorSkyblock2] Finished loading 0 islands (Took 5ms)
> > > 
> > > 
> > > Are there any islands in the database..?
> > > ![image](https://user-images.githubusercontent.com/31826333/193647214-e5e3e1c7-dd80-4796-9b50-a083fd5c83b6.png)
> > > nop (this is after a restart, and before the restart I created an island)
> 
> Weird, looks like your database got wiped? Are you able to restore a backup (The plugin automatically makes backups)

I deleted all my backups today, and resetted database, so I don't get any database :/
You can't reproduce it on your side ?

**Comment by OmerBenGera** [comment]
> > > > > On latest dev build, each restart, users aren't member anymore of their island, and it creates a new island when they do /is
> > > > > and islands aren't save in database : [SuperiorSkyblock2] Starting to load islands... [SuperiorSkyblock2] Finished loading 0 islands (Took 5ms)
> > > > 
> > > > 
> > > > Are there any islands in the database..?
> > > > ![image](https://user-images.githubusercontent.com/31826333/193647214-e5e3e1c7-dd80-4796-9b50-a083fd5c83b6.png)
> > > > nop (this is after a restart, and before the restart I created an island)
> > 
> > 
> > Weird, looks like your database got wiped? Are you able to restore a backup (The plugin automatically makes backups)
> 
> I deleted all my backups today, and resetted database, so I don't get any database :/ You can't reproduce it on your side ?

Ah, so the wipe was intended?

**Comment by Vxrtebs** [comment]
> > > Check out for errors, let me know if you find any. Btw, there's no need to mention me.
> > 
> > 
> > theres no errors in the logs
> 
> Mind sending me your logs file, I'd like to take a look at it myself as well.

[latest (18).log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9700214/latest.18.log)

**Comment by OmerBenGera** [comment]
Not sure why it occurs, as it works fine for me.
Execute the following command: `/is admin debug DATABASE_QUERY`, then create an island.
Look for messages in console and report back.

**Comment by OmerBenGera** [comment]
As you can see, the plugin executes the sql commands correctly.
It means that its something to do with your database. Try deleting the file and see if it helps. If not, I'd advice to switch to MySQL.

**Comment by Vxrtebs** [comment]
> As you can see, the plugin executes the sql commands correctly, which means its something to do with your database. Try deleting the database file and see if it helps. If not, I'd advice to switch to MySQL.

it didnt help, it only deleted all data, how can i open the backup?

**Comment by OmerBenGera** [comment]
> > As you can see, the plugin executes the sql commands correctly, which means its something to do with your database. Try deleting the database file and see if it helps. If not, I'd advice to switch to MySQL.
> 
> it didnt help, it only deleted all data, how can i open the backup?

The automated backup of the plugin? It's a zip file containing the datastore folder, which includes the database file inside it.
Anyways the issue should be fixed with latest dev build.

**Comment by Vxrtebs** [comment]
> > > As you can see, the plugin executes the sql commands correctly, which means its something to do with your database. Try deleting the database file and see if it helps. If not, I'd advice to switch to MySQL.
> > 
> > 
> > it didnt help, it only deleted all data, how can i open the backup?
> 
> The automated backup of the plugin? It's a zip file containing the datastore folder, which includes the database file inside it. Anyways the issue should be fixed with latest dev build.

lmk when it is fixed, ty

**Comment by OmerBenGera** [comment]
> > > > As you can see, the plugin executes the sql commands correctly, which means its something to do with your database. Try deleting the database file and see if it helps. If not, I'd advice to switch to MySQL.
> > > 
> > > 
> > > it didnt help, it only deleted all data, how can i open the backup?
> > 
> > 
> > The automated backup of the plugin? It's a zip file containing the datastore folder, which includes the database file inside it. Anyways the issue should be fixed with latest dev build.
> 
> lmk when it is fixed, ty

The issue was already been fixed.

**Comment by Vxrtebs** [comment]
> > > > > As you can see, the plugin executes the sql commands correctly, which means its something to do with your database. Try deleting the database file and see if it helps. If not, I'd advice to switch to MySQL.
> > > > 
> > > > 
> > > > it didnt help, it only deleted all data, how can i open the backup?
> > > 
> > > 
> > > The automated backup of the plugin? It's a zip file containing the datastore folder, which includes the database file inside it. Anyways the issue should be fixed with latest dev build.
> > 
> > 
> > lmk when it is fixed, ty
> 
> The issue was already been fixed (confirmed by multiples already)

i downloaded latest dev build and its not fixed Xd

**Comment by OmerBenGera** [comment]
> > > > > > As you can see, the plugin executes the sql commands correctly, which means its something to do with your database. Try deleting the database file and see if it helps. If not, I'd advice to switch to MySQL.
> > > > > 
> > > > > 
> > > > > it didnt help, it only deleted all data, how can i open the backup?
> > > > 
> > > > 
> > > > The automated backup of the plugin? It's a zip file containing the datastore folder, which includes the database file inside it. Anyways the issue should be fixed with latest dev build.
> > > 
> > > 
> > > lmk when it is fixed, ty
> > 
> > 
> > The issue was already been fixed (confirmed by multiples already)
> 
> i downloaded latest dev build and its not fixed Xd

What's not working for you exactly?

**Comment by Vxrtebs** [comment]
> > > > > > > As you can see, the plugin executes the sql commands correctly, which means its something to do with your database. Try deleting the database file and see if it helps. If not, I'd advice to switch to MySQL.
> > > > > > 
> > > > > > 
> > > > > > it didnt help, it only deleted all data, how can i open the backup?
> > > > > 
> > > > > 
> > > > > The automated backup of the plugin? It's a zip file containing the datastore folder, which includes the database file inside it. Anyways the issue should be fixed with latest dev build.
> > > > 
> > > > 
> > > > lmk when it is fixed, ty
> > > 
> > > 
> > > The issue was already been fixed (confirmed by multiples already)
> > 
> > 
> > i downloaded latest dev build and its not fixed Xd
> 
> What's not working for you exactly?

its still the same, players cant teleport to their islands

**Comment by OmerBenGera** [comment]
> > > > > > > > As you can see, the plugin executes the sql commands correctly, which means its something to do with your database. Try deleting the database file and see if it helps. If not, I'd advice to switch to MySQL.
> > > > > > > 
> > > > > > > 
> > > > > > > it didnt help, it only deleted all data, how can i open the backup?
> > > > > > 
> > > > > > 
> > > > > > The automated backup of the plugin? It's a zip file containing the datastore folder, which includes the database file inside it. Anyways the issue should be fixed with latest dev build.
> > > > > 
> > > > > 
> > > > > lmk when it is fixed, ty
> > > > 
> > > > 
> > > > The issue was already been fixed (confirmed by multiples already)
> > > 
> > > 
> > > i downloaded latest dev build and its not fixed Xd
> > 
> > 
> > What's not working for you exactly?
> 
> its still the same, players cant teleport to their islands

What happens when they try to teleport?
Do they get any messages?

**Comment by Vxrtebs** [comment]
> > > > > > > > > As you can see, the plugin executes the sql commands correctly, which means its something to do with your database. Try deleting the database file and see if it helps. If not, I'd advice to switch to MySQL.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > it didnt help, it only deleted all data, how can i open the backup?
> > > > > > > 
> > > > > > > 
> > > > > > > The automated backup of the plugin? It's a zip file containing the datastore folder, which includes the database file inside it. Anyways the issue should be fixed with latest dev build.
> > > > > > 
> > > > > > 
> > > > > > lmk when it is fixed, ty
> > > > > 
> > > > > 
> > > > > The issue was already been fixed (confirmed by multiples already)
> > > > 
> > > > 
> > > > i downloaded latest dev build and its not fixed Xd
> > > 
> > > 
> > > What's not working for you exactly?
> > 
> > 
> > its still the same, players cant teleport to their islands
> 
> What happens when they try to teleport? Do they get any messages?

"you have been teleported to your island" and they re getting teleported to spawn or in the middle on nowhere

**Comment by OmerBenGera** [comment]
> Reference in

I think their island home is for no reason no inside their island area.
Does it happen for all the players or only for some?

**Comment by Vxrtebs** [comment]
> > Reference in
> 
> I think their island home is for no reason no inside their island area. Does it happen for all the players or only for some?

only for some, but they cant teleport to it after creating it

**Comment by OmerBenGera** [comment]
> > > Reference in
> > 
> > 
> > I think their island home is for no reason no inside their island area. Does it happen for all the players or only for some?
> 
> only for some, but they cant teleport to it after creating it

Tell them to re-create their island.
I think what happened is that their island home location is not in the area of the island, which causes them to get teleported back to spawn by the plugin.
Recreating the islands should fix the issue.

**Comment by Vxrtebs** [comment]
> > > > Reference in
> > > 
> > > 
> > > I think their island home is for no reason no inside their island area. Does it happen for all the players or only for some?
> > 
> > 
> > only for some, but they cant teleport to it after creating it
> 
> Tell them to re-create their island. I think what happened is that their island home location is not in the area of the island, which causes them to get teleported back to spawn by the plugin. Recreating the islands should fix the issue.

i told a player to do this, and when he created the island again the same thing happened to him

**Comment by OmerBenGera** [comment]
> > > > > Reference in
> > > > 
> > > > 
> > > > I think their island home is for no reason no inside their island area. Does it happen for all the players or only for some?
> > > 
> > > 
> > > only for some, but they cant teleport to it after creating it
> > 
> > 
> > Tell them to re-create their island. I think what happened is that their island home location is not in the area of the island, which causes them to get teleported back to spawn by the plugin. Recreating the islands should fix the issue.
> 
> i told a player to do this, and when he created the island again the same thing happened to him

Try replicating the issue yourself and not through your players.

**Comment by Vxrtebs** [comment]
> > > > > > Reference in
> > > > > 
> > > > > 
> > > > > I think their island home is for no reason no inside their island area. Does it happen for all the players or only for some?
> > > > 
> > > > 
> > > > only for some, but they cant teleport to it after creating it
> > > 
> > > 
> > > Tell them to re-create their island. I think what happened is that their island home location is not in the area of the island, which causes them to get teleported back to spawn by the plugin. Recreating the islands should fix the issue.
> > 
> > 
> > i told a player to do this, and when he created the island again the same thing happened to him
> 
> Try replicating the issue yourself and not through your players.

i got the issue by myself, i tried deleting and creating the island again but this bug still occurs

https://cdn.discordapp.com/attachments/927523775631753246/1028349960275628113/Minecraft__1.18_-_Multiplayer_3rd-party_Server_2022-10-08_18-51-11_Trim.mp4

**Comment by OmerBenGera** [comment]
> > > > > > > Reference in
> > > > > > 
> > > > > > 
> > > > > > I think their island home is for no reason no inside their island area. Does it happen for all the players or only for some?
> > > > > 
> > > > > 
> > > > > only for some, but they cant teleport to it after creating it
> > > > 
> > > > 
> > > > Tell them to re-create their island. I think what happened is that their island home location is not in the area of the island, which causes them to get teleported back to spawn by the plugin. Recreating the islands should fix the issue.
> > > 
> > > 
> > > i told a player to do this, and when he created the island again the same thing happened to him
> > 
> > 
> > Try replicating the issue yourself and not through your players.
> 
> i got the issue by myself, i tried deleting and creating the island again but this bug still occurs
> 
> https://cdn.discordapp.com/attachments/927523775631753246/1028349960275628113/Minecraft__1.18_-_Multiplayer_3rd-party_Server_2022-10-08_18-51-11_Trim.mp4

Upload the video to youtube (or any other online streaming service) and send me a link here.

**Comment by Vxrtebs** [comment]
> > > > > > > > Reference in
> > > > > > > 
> > > > > > > 
> > > > > > > I think their island home is for no reason no inside their island area. Does it happen for all the players or only for some?
> > > > > > 
> > > > > > 
> > > > > > only for some, but they cant teleport to it after creating it
> > > > > 
> > > > > 
> > > > > Tell them to re-create their island. I think what happened is that their island home location is not in the area of the island, which causes them to get teleported back to spawn by the plugin. Recreating the islands should fix the issue.
> > > > 
> > > > 
> > > > i told a player to do this, and when he created the island again the same thing happened to him
> > > 
> > > 
> > > Try replicating the issue yourself and not through your players.
> > 
> > 
> > i got the issue by myself, i tried deleting and creating the island again but this bug still occurs
> > https://cdn.discordapp.com/attachments/927523775631753246/1028349960275628113/Minecraft__1.18_-_Multiplayer_3rd-party_Server_2022-10-08_18-51-11_Trim.mp4
> 
> Upload the video to youtube (or any other online streaming service) and send me a link here.

https://streamable.com/i73bid

**Comment by OmerBenGera** [comment]
> > > > > > > > > Reference in
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I think their island home is for no reason no inside their island area. Does it happen for all the players or only for some?
> > > > > > > 
> > > > > > > 
> > > > > > > only for some, but they cant teleport to it after creating it
> > > > > > 
> > > > > > 
> > > > > > Tell them to re-create their island. I think what happened is that their island home location is not in the area of the island, which causes them to get teleported back to spawn by the plugin. Recreating the islands should fix the issue.
> > > > > 
> > > > > 
> > > > > i told a player to do this, and when he created the island again the same thing happened to him
> > > > 
> > > > 
> > > > Try replicating the issue yourself and not through your players.
> > > 
> > > 
> > > i got the issue by myself, i tried deleting and creating the island again but this bug still occurs
> > > https://cdn.discordapp.com/attachments/927523775631753246/1028349960275628113/Minecraft__1.18_-_Multiplayer_3rd-party_Server_2022-10-08_18-51-11_Trim.mp4
> > 
> > 
> > Upload the video to youtube (or any other online streaming service) and send me a link here.
> 
> https://streamable.com/i73bid

Very weird - it's like you are teleported outside of the world border.
Are you able to replicate the issue on a server with only SSB installed?

**Comment by Vxrtebs** [comment]
> > > > > > > > > > Reference in
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I think their island home is for no reason no inside their island area. Does it happen for all the players or only for some?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > only for some, but they cant teleport to it after creating it
> > > > > > > 
> > > > > > > 
> > > > > > > Tell them to re-create their island. I think what happened is that their island home location is not in the area of the island, which causes them to get teleported back to spawn by the plugin. Recreating the islands should fix the issue.
> > > > > > 
> > > > > > 
> > > > > > i told a player to do this, and when he created the island again the same thing happened to him
> > > > > 
> > > > > 
> > > > > Try replicating the issue yourself and not through your players.
> > > > 
> > > > 
> > > > i got the issue by myself, i tried deleting and creating the island again but this bug still occurs
> > > > https://cdn.discordapp.com/attachments/927523775631753246/1028349960275628113/Minecraft__1.18_-_Multiplayer_3rd-party_Server_2022-10-08_18-51-11_Trim.mp4
> > > 
> > > 
> > > Upload the video to youtube (or any other online streaming service) and send me a link here.
> > 
> > 
> > https://streamable.com/i73bid
> 
> Very weird - it's like you are teleported outside of the world border. Are you able to replicate the issue on a server with only SSB installed (with the same configuration of the plugin)

ill try tmr

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Vxrtebs** [comment]
> Any news regarding this?

i cant test it bc i dont have any other server, and it only happens when like 100+ islands are created

**Comment by OmerBenGera** [comment]
> > Any news regarding this?
> 
> i cant test it bc i dont have any other server, and it only happens when like 100+ islands are created

Try it on your localhost.

**Comment by Vxrtebs** [comment]
> > > Any news regarding this?
> > 
> > 
> > i cant test it bc i dont have any other server, and it only happens when like 100+ islands are created
> 
> Try it on your localhost.

ok

**Comment by Vxrtebs** [comment]
i tried, and everything was normal, i think bc it only happens when like 100+ island are created, if u want u can try to get the bug on my server

**Comment by OmerBenGera** [comment]
> i tried, and everything was normal, i think bc it only happens when like 100+ island are created, if u want u can try to get the bug on my server

I don't see how the amount of islands in your server will somehow affect such thing.
Try yourself replicating the issue with a newly created island on your server.

**Comment by OmerBenGera** [comment]
> i tried, and everything was normal, i think bc it only happens when like 100+ island are created, if u want u can try to get the bug on my server

Show me your server.properties file

**Comment by Vxrtebs** [comment]
sorry for late reply, i werent at home

#Minecraft server properties
#Sun Oct 16 19:10:46 CEST 2022
rcon.port=55555
enable-command-block=true
gamemode=survival
pvp=true
network-compression-threshold=-1
max-tick-time=60000
max-players=500
online-mode=false
max-build-height=256
resource-pack-prompt=
allow-nether=false
rcon.password=test34567a
force-gamemode=false
white-list=false
spawn-npcs=false
function-permission-level=2
level-type=default
text-filtering-config=
max-world-size=3000
enable-jmx-monitoring=false
level-seed=
enable-query=false
generator-settings=
level-name=world
motd=motd
query.port=11243
generate-structures=true
difficulty=easy
require-resource-pack=false
use-native-transport=true
enable-status=true
allow-flight=true
broadcast-rcon-to-ops=true
view-distance=4
server-ip=0.0.0.0
server-port=11243
enable-rcon=false
sync-chunk-writes=true
server-name=motd
op-permission-level=4
prevent-proxy-connections=false
resource-pack=
entity-broadcast-range-percentage=100
server-id=unnamed
player-idle-timeout=0
debug=false
rate-limit=0
hardcore=false
broadcast-console-to-ops=false
spawn-animals=true
snooper-enabled=false
spawn-monsters=true
enforce-whitelist=false
spawn-protection=1
resource-pack-sha1=

**Comment by Vxrtebs** [comment]
i cant send the file

**Comment by OmerBenGera** [comment]
Why is your world has a max size of 3000?
```max-world-size=3000```
This what causes the issue to occur, and it also makes sense - after around 100~ islands, islands are starting to generate beyond the 3000 limit you configured, which causes the teleportation to occur.
Increase this value and it will work again :)

**Comment by Vxrtebs** [comment]
> Why is your world has a max size of 3000? `max-world-size=3000` This what causes the issue to occur, and it also makes sense - after around 100~ islands, islands are starting to generate beyond the 3000 limit you configured, which causes the teleportation to occur. Increase this value and it will work again :)

bruh i didnt see it, sorry

**Comment by OmerBenGera** [comment]
> > Why is your world has a max size of 3000? `max-world-size=3000` This what causes the issue to occur, and it also makes sense - after around 100~ islands, islands are starting to generate beyond the 3000 limit you configured, which causes the teleportation to occur. Increase this value and it will work again :)
> 
> bruh i didnt see it, sorry

All's good. Let me know if it fixes the issue.
I will also make sure to add warning for such thing in the future (even tho it's not really an issue with the plugin), as you're not the first one to have this issue

**Comment by Vxrtebs** [comment]
> > > Why is your world has a max size of 3000? `max-world-size=3000` This what causes the issue to occur, and it also makes sense - after around 100~ islands, islands are starting to generate beyond the 3000 limit you configured, which causes the teleportation to occur. Increase this value and it will work again :)
> > 
> > 
> > bruh i didnt see it, sorry
> 
> All's good. Let me know if it fixes the issue. I will also make sure to add warning for such thing in the future (even tho it's not really an issue with the plugin), as you're not the first one to have this issue

it works now, thank you 😀

**Comment by OmerBenGera** [comment]
> Author

Amazing!
I also added a warning in latest dev build.

I am closing this :)
