### ISSUE TITLE
EnchantingMission issue + flags nbt

### ISSUE THREAD

**Issue by AlmostPanda** [BG-Software-LLC/SuperiorSkyblock2#2207]
### Minecraft's Version

Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Plugin's Version

2024.2-b300

### Describe the bug

When I try to complete `EnchantingMissions` using the required item + enchanted book in anvil it outputs an error in console and doesnt count the progress to mission
(when getting the enchant on item using enchanting table it works normally)

error: https://pastebin.com/DSis0r4P

about the nbt flag part
if I use a weapon/tool/armor as icon for mission and add the
```
flags:
  - HIDE_ATTRIBUTES
```
it doesnt seem to work (using offical mc launcher + no resourcepack)

here is our mission if you would like to try
[FullGear.zip](https://github.com/user-attachments/files/16726912/FullGear.zip)

### To Reproduce

1. Create EnchantingMission
2. Use the required item + enchanted book in anvil
3. check console

nbt part
1. create a mission with a weapon or armor as icon
2. add flag: HIDE_ATTRIBUTES
3. check mission

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by AlmostPanda** [comment]
the error from using anvil to complete the mission is fixed, but the flag nbt part isnt
still can see attributes
![image](https://github.com/user-attachments/assets/d391159e-5cf3-440b-8862-9d75a1e00ff7)

**Comment by OmerBenGera** [comment]
You're right, it doesn't work in 1.21 for no reason
However, I tested it on 1.20.4 and it seems to work just fine, so I suspect it is a bug in Spigot/Paper.

**Comment by AlmostPanda** [comment]
just tried latest paper version for 1.21.1 and still doesn't work
rip

**Comment by OmerBenGera** [comment]
> just tried latest paper version for 1.21.1 and still doesn't work rip

Try removing ViaVersion, maybe this is the cause?

**Comment by AlmostPanda** [comment]
its not, using only SSB

**Comment by OmerBenGera** [comment]
Report it over Paper/Spigot.

**Comment by AlmostPanda** [comment]
seems to be reported, but I dont understand a thing, is it somehow fixed?

https://github.com/PaperMC/Paper/issues/10655

**Comment by OmerBenGera** [comment]
> seems to be reported, but I dont understand a thing, is it somehow fixed?
> 
> [PaperMC/Paper#10655](https://github.com/PaperMC/Paper/issues/10655)
> 
> edit: found this, maybe it helps you https://www.spigotmc.org/threads/i-cant-add-attributes-to-the-itemstack.656049/

Make a feature request for this, I can't really consider it as a bug.
If the HIDE_ATTRIBUTES does not work on Paper, then it's not a bug from my side.
I might need to implement a way to hide attributes, but it's a new feature request.

**Comment by AlmostPanda** [comment]
just to make sure, by "make a feature request" you mean on your github or Paper?

**Comment by OmerBenGera** [comment]
> just to make sure, by "make a feature request" you mean on your github or Paper?

on my github :)
