### ISSUE TITLE
World issues

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#309]
**Minecraft's Version**
Paper 1.16.5

**Plugin's Version**: -
Tried 1.7.0 and deb build-167 and 168

**Describe the bug**
On server restart, config is not loaded correctly, and it "fully reset" islands, as for example I renamed in config my islands world "SuperiorWorld" to "Iles" and after a restart it creates AGAIN the "SuperiorWorld" and set it as a default island world

**To Reproduce**
Create a server on b160, rename the worlds in config, create an island on the new world, upgrade to superior 1.7.0, then you won't get your island

**Additional information**
It worked well on superior b160

**Comment by OmerBenGera** [comment]
You must delete the database file in order to change the world's name.

**Comment by WarnDangerous** [comment]
What I try to explain, it's that everything worked perfectly before, I got my world renaimed since many month, but when I switch to superior 1.7.0, it doesn't take the custom world name, and create the default world

**Comment by OmerBenGera** [comment]
It worked fine for me when I tried to change the world's name in 1.7.0. However, it might been an issue when converting from old version to new one, so I'll test that as well and come back to you

**Comment by WarnDangerous** [comment]
I can confirm the issue is when the config is upgraded to 1.7.0, it doesn't save the world name, and reset it to "SuperiorWorld"

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build

**Comment by WarnDangerous** [comment]
It works, but I had to manually re-edit the world in config and restart the server in order to work (I came from b160 to b169)

**Comment by OmerBenGera** [comment]
There's no need to manually edit anything. If you had your world-name as something else in older versions, the new dev build will save that name.
I am closing this for now

**Comment by WarnDangerous** [comment]
After each restart it reset me to "world-name: SuperiorWorld", (using b169), but when I'm on b160, after each restart it keeps the "world-name: Iles"; so there is still an issue for me

**Comment by WarnDangerous** [comment]
Edit :
I deleted my database to fix this error

**Comment by OmerBenGera** [comment]
> 
> 
> After each restart it reset me to "world-name: SuperiorWorld", (using b169), but when I'm on b160, after each restart it keeps the "world-name: Iles"; so there is still an issue for me

As I said before, you must delete the database in order to change world names.
